server:
  port: 80
  
spring:
  application:
    name: tableau-gateway
  cloud:
    gateway:  
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
      routes:  
      - id: jscript
        uri: http://localhost:81
        predicates:
        - Path=/doc/**          
      - id: tableau
        uri: http://localhost:82
        predicates:
        - Path=/**                